version: "2"
services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./raptor-auth-service/src/main/resources/sql:/docker-entrypoint-initdb.d
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: raptor
    networks:
      - raptor_net

  busybox:
    image: busybox
    container_name: busybox
    volumes:
      - ./:/raptor
    networks:
      - raptor_net

  dbadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dbadmin
    environment:
      MYSQL_ROOT_PASSWORD: raptor
    restart: always
    ports:
     - 8081:80
    volumes:
     - ./data/phpmyadmin:/sessions
    links:
      - mariadb:db
    networks:
      - raptor_net

  mongoadmin:
    image: adicom/admin-mongo
    container_name: mongoadmin
    # environment:
    restart: always
    ports:
     - 8082:1234
    # volumes:
    links:
      - mongo
    networks:
      - raptor_net

  mongo:
    image: mongo:3
    container_name: mongo
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    command: --smallfiles # --rest --auth
    networks:
      - raptor_net
