version: "2"
services:

  mongoadmin:
    image: adicom/admin-mongo
    # environment:
    restart: always
    ports:
     - 8082:1234
    # volumes:
    links:
      - mongo

  mongo:
    image: mongo:3
    container_name: mongo
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    command: --smallfiles --setParameter failIndexKeyTooLong=false
