version: "2"

networks:
  raptor_net:
    driver: bridge

services:

  api:
    image: raptorbox/api
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./config:/etc/raptor
    depends_on:
      - elasticsearch
      - couchbase
    networks:
      - raptor_net
    logging:
      driver: journald
      options:
         tag: {{.Name}}

  broker:
    image: raptorbox/broker
    ports:
      - 1883:1883
    volumes:
      - ./config:/etc/raptor
    depends_on:
      - elasticsearch
    networks:
      - raptor_net
    logging:
      driver: journald
      options:
         tag: {{.Name}}

  auth:
    image: raptorbox/auth
#    ports:
#      - 8090:8090
    expose:
      - 8090
    volumes:
      - ./config:/etc/raptor
    depends_on:
      - mariadb
    networks:
      - raptor_net
    logging:
      driver: journald
      options:
         tag: {{.Name}}

  mariadb:
    image: mariadb:latest
    container_name: mariadb
#    ports:
#      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./raptor-auth-service/src/main/resources/sql:/docker-entrypoint-initdb.d
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: raptor
    networks:
      - raptor_net
    logging:
      driver: journald
      options:
         tag: {{.Name}}

  couchbase:
    image: couchbase/server
    volumes:
      - ./data/couchbase:/opt/couchbase/var
#    ports:
#      - 8091:8091
#      - 8092:8092
#      - 8093:8093
#      - 11210:11210
    expose:
      - 8091
      - 8092
      - 8093
      - 11210
    networks:
      - raptor_net
    logging:
      driver: journald

  elasticsearch:
    image: elasticsearch:5
    command: elasticsearch -E cluster.name="raptor" -E path.data=/usr/share/elasticsearch/data -E transport.host=0.0.0.0
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300
    expose:
      - 9200
      - 9300
    networks:
      - raptor_net
    logging:
      driver: journald
      options:
         tag: {{.Name}}

  proxy:
    image: raptorbox/proxy
    ports:
      - 9090:80
    depends_on:
      - api
      - auth
      - broker
    networks:
      - raptor_net
    logging:
      driver: journald
      options:
         tag: {{.Name}}
