version: "2"

networks:
  raptor_net:
    driver: bridge

services:

  broker:
    image: raptorbox/broker
    ports:
      - 1883:1883
    volumes:
      - ./config:/etc/raptor
    networks:
      - raptor_net

  action:
    image: raptorbox/action
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  inventory:
    image: raptorbox/inventory
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  profile:
    image: raptorbox/profile
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  stream:
    image: raptorbox/stream
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  tree:
    image: raptorbox/tree
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  auth:
    image: raptorbox/auth
    volumes:
      - ./config:/etc/raptor
    links:
      - mariadb
    depends_on:
      - mariadb
      - broker
    networks:
      - raptor_net

  apigateway:
    image: raptorbox/gateway
    volumes:
      - ./config:/etc/raptor
    networks:
      - raptor_net

  curl:
    image: byrnedo/alpine-curl
    volumes:
      - ./:/raptor
    networks:
      - raptor_net

  mariadb:
    image: mariadb:latest
    volumes:
      - ./raptor-auth/src/main/resources/sql:/docker-entrypoint-initdb.d
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: raptor
    networks:
      - raptor_net

  mongo:
    image: mongo:3
    volumes:
      - ./data/mongodb:/data/db
    command: --smallfiles # --rest --auth
    networks:
      - raptor_net
