version: "2"

networks:
  raptor_net:
    driver: bridge

services:

  broker:
    image: raptorbox/standalone:v4
    ports:
      - 1883:1883
    volumes:
      - ./config:/etc/raptor
      - ./data:/data
    networks:
      - raptor_net
    logging:
      driver: json-file
      options:
        max-size: 100m

  mariadb:
    image: mariadb:latest
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: raptor
      MYSQL_DATABASE: raptor
    networks:
      - raptor_net

  mongo:
    image: mongo:3
    volumes:
      - ./data/mongodb:/data/db
    command: --smallfiles --setParameter failIndexKeyTooLong=false
    networks:
      - raptor_net

  ui:
    image: raptorbox/raptor-ui
    networks:
      - raptor_net

  apigateway:
    image: nginx
    volumes:
      - ./config/nginx.standalone.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
        - ui
        - broker
    command: nginx -g 'daemon off;'
    networks:
      - raptor_net
