version: "2"

networks:
  raptor_net:
    driver: bridge

services:

  broker:
    build: ./raptor-broker
    container_name: raptor-broker
    ports:
      - 1883:1883
    volumes:
      - ./config:/etc/raptor
    networks:
      - raptor_net

  action:
    build: ./raptor-api/raptor-action
    container_name: raptor-action
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  inventory:
    build: ./raptor-api/raptor-inventory
    container_name: raptor-inventory
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  profile:
    build: ./raptor-api/raptor-profile
    container_name: raptor-profile
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  stream:
    build: ./raptor-api/raptor-stream
    container_name: raptor-stream
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  tree:
    build: ./raptor-api/raptor-tree
    container_name: raptor-tree
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  auth:
    build: ./raptor-api/raptor-auth
    container_name: raptor-auth
    volumes:
      - ./config:/etc/raptor
    links:
      - mariadb
    depends_on:
      - mariadb
      - broker
    networks:
      - raptor_net

  apigateway:
    build: ./raptor-api/raptor-gateway
    container_name: raptor-gateway
    volumes:
      - ./config:/etc/raptor
    networks:
      - raptor_net

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    volumes:
      - ./raptor-auth/src/main/resources/sql:/docker-entrypoint-initdb.d
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: raptor
    networks:
      - raptor_net
    ports:
        - 3306:3306

  busybox:
    image: busybox
    container_name: busybox
    volumes:
      - ./:/raptor
    networks:
      - raptor_net

  dbadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: raptor
    restart: always
    volumes:
     - ./data/phpmyadmin:/sessions
    links:
      - mariadb:db
    networks:
      - raptor_net
    ports:
        - 8081:80

  mongoadmin:
    image: adicom/admin-mongo
    # environment:
    restart: always
    # volumes:
    links:
      - mongo
    networks:
      - raptor_net
    ports:
        - 8082:1234
  mongo:
    image: mongo:3
    container_name: mongo
    volumes:
      - ./data/mongodb:/data/db
    command: --smallfiles # --rest --auth
    networks:
      - raptor_net
    ports:
        - 27017:27017
