version: "2"

networks:
  raptor_test:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1

services:

  api:
    image: raptorbox/standalone:v5
    ports:
      - 10090:80
    volumes:
      - ./config:/etc/raptor
      - ./data:/data
    networks:
      - raptor_test
    extra_hosts:
      - "raptor.local:172.16.238.1"

  broker:
    image: raptorbox/broker:v5
    ports:
      - 1883:1883
      - 8880:8880
    depends_on:
      - mongo
    environment:
        DEBUG: r*
        LOG_LEVEL: debug
    networks:
      - raptor_test
    logging:
      driver: json-file
      options:
        max-size: 1024m
    extra_hosts:
      - "raptor.local:172.16.238.1"

  auth:
    image: raptorbox/auth:v5
    ports:
      - 10094:10094
    depends_on:
      - mongo
      - redis
    environment:
        DEBUG: r*
        LOG_LEVEL: debug
    networks:
      - raptor_test
    logging:
      driver: json-file
      options:
        max-size: 1024m
    extra_hosts:
      - "raptor.local:172.16.238.1"

  app:
    image: raptorbox/app:v5
    ports:
      - 10095:10095
    depends_on:
      - mongo
      - redis
    environment:
        DEBUG: r*
        LOG_LEVEL: debug
    networks:
      - raptor_test
    logging:
      driver: json-file
      options:
        max-size: 1024m
    extra_hosts:
      - "raptor.local:172.16.238.1"

  mariadb:
    image: mariadb:latest
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: raptor
    networks:
      - raptor_test
    ports:
        - 3306:3306

  dbadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: raptor
    restart: always
    volumes:
     - ./data/phpmyadmin:/sessions
    links:
      - mariadb:db
    networks:
      - raptor_test
    ports:
        - 8081:80

  mongoadmin:
    image: adicom/admin-mongo
    # environment:
    restart: always
    # volumes:
    links:
      - mongo
    networks:
      - raptor_test
    ports:
        - 8082:1234
  mongo:
    image: mongo:3
    volumes:
      - ./data/mongodb:/data/db
    command: --smallfiles --setParameter failIndexKeyTooLong=false
    networks:
      - raptor_test
    ports:
        - 27017:27017

  redis:
    image: redis
    networks:
      - raptor_test
    ports:
        - 6379:6379

  apigateway:
    image: nginx
    volumes:
      - ./config/nginx.standalone.test.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    command: nginx -g 'daemon off;'
    networks:
      - raptor_test


  redis:
    image: redis
    networks:
      - raptor_test
    ports:
        - 6379:6379
