version: "2"

networks:
  raptor_net:
    driver: bridge

services:

  broker:
    build: ./raptor-broker
    container_name: raptor-broker
    ports:
      - 1883:1883
    volumes:
      - ./config:/etc/raptor
    networks:
      - raptor_net

  action:
    build: ./raptor-api/raptor-action
    container_name: raptor-action
    ports:
      - 8050:8050
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  inventory:
    build: ./raptor-api/raptor-inventory
    container_name: raptor-inventory
    ports:
      - 8060:8060
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  profile:
    build: ./raptor-api/raptor-profile
    container_name: raptor-profile
    ports:
      - 8070:8070
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  stream:
    build: ./raptor-api/raptor-stream
    container_name: raptor-stream
    ports:
      - 8080:8080
    volumes:
      - ./config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - raptor_net

  auth:
    build: ./raptor-api/raptor-auth-service
    container_name: raptor-auth-service
    ports:
      - 8090:8090
    volumes:
      - ./config:/etc/raptor
    links:
      - mariadb
    depends_on:
      - mariadb
      - broker
    networks:
      - raptor_net

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./raptor-auth-service/src/main/resources/sql:/docker-entrypoint-initdb.d
      - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: raptor
    networks:
      - raptor_net

  busybox:
    image: busybox
    container_name: busybox
    volumes:
      - ./:/raptor
    networks:
      - raptor_net

  dbadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dbadmin
    environment:
      MYSQL_ROOT_PASSWORD: raptor
    restart: always
    ports:
     - 8081:80
    volumes:
     - ./data/phpmyadmin:/sessions
    links:
      - mariadb:db
    networks:
      - raptor_net

  mongo:
    image: mongo:3
    container_name: mongo
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    command: --smallfiles # --rest --auth
    networks:
      - raptor_net


  rproxy:
    build: ./docker/proxy
    depends_on:
      # - stream
      - action
      - inventory
      - auth
      - broker
    networks:
      - raptor_net
