
spring:
  devtools:
    restart:
      enabled: true
      trigger-file: raptor-data-1.0.jar
      additional-paths: target
  profiles: default
  mongodb:
    host: localhost
    port: 27017
    database: raptor
#    username: admin
#    password: admin
    
server:
  contextPath: /data
  port: 8040
  address: 127.0.0.1
  error:
    whitelabel:
      enabled: true

logging:
  level:
#    root: INFO
#    org.springframework.security: DEBUG
    org.createnet.raptor.profile: DEBUG
    org.createnet.raptor: DEBUG
    org.springframework.data.mongodb.core.index: OFF

raptor:
    url: http://raptor.local
    auth:
        header: Authorization
        headerPrefix: Bearer
    