spring:

  datasource:
    url: jdbc:mariadb://mariadb:3306/raptor?createDatabaseIfNotExist=true
    username: root
    password: raptor
    driverClassName: org.mariadb.jdbc.Driver
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    testOnBorrow: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    lastInsertQuery: SELECT LAST_INSERT_ID()

  jpa:
    show-sql: false

    # Hibernate ddl auto (none, validate, update, create, create-drop)
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl: true
        ddl-auto: validate
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        cache:
            use_second_level_cache: true
            use_query_cache: true
            region:
                factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

  devtools:
    restart:
      enabled: true
      trigger-file: raptor-${spring.config.name}-1.0.jar
      additional-paths: target

flyway:
  # locations: db/migration/{vendor}
  enabled: true
