
authUrl: http://auth:8090
artemisConfiguration: file:///etc/raptor/broker.xml
users:
  - name: frontend
    password: frontend42
    roles:
      - admin
  - name: system
    password: system123
    roles:
      - admin
