
server:
  contextPath: /

zuul:
    routes:
        action:
            path: /action/**
            url: http://action
        inventory:
            path: /inventory/**
            url: http://inventory
        profile:
            path: /profile/**
            url: http://profile
        stream:
            path: /stream/**
            url: http://stream
        tree:
            path: /tree/**
            url: http://tree
        auth:
            path: /auth/**
            url: http://auth

ribbon:
    eureka:
        enabled: false
