
server:
  contextPath: /

zuul:
    routes:
        action:
            path: /action/**
            url: http://action/action
            sensitiveHeaders: Authorization
        inventory:
            path: /inventory/**
            url: http://inventory/inventory
            sensitiveHeaders: Authorization
        profile:
            path: /profile/**
            url: http://profile/profile
            sensitiveHeaders: Authorization
        stream:
            path: /stream/**
            url: http://stream/stream
            sensitiveHeaders: Authorization
        tree:
            path: /tree/**
            url: http://tree/tree
            sensitiveHeaders: Authorization
        auth:
            path: /auth/**
            url: http://auth/auth
            sensitiveHeaders: Authorization

ribbon:
    eureka:
        enabled: false
