
server:
  contextPath: /

zuul:
    # stripPrefix: false
    sensitiveHeaders:
    routes:
        action:
            path: /action/**
            url: http://action/action
        inventory:
            path: /inventory/**
            url: http://inventory/inventory
        profile:
            path: /profile/**
            url: http://profile/profile
        stream:
            path: /stream/**
            url: http://stream/stream
        tree:
            path: /tree/**
            url: http://tree/tree
        auth:
            path: /auth/**
            url: http://auth/auth

ribbon:
    eureka:
        enabled: false
