
# maximum limit of data record to be fetched per request. default: 1000
recordFetchLimit: 1000

type: elasticsearch
elasticsearch:
  type: transport
  clientConfig:
    cluster.name: raptor
  transport:
    host: elasticsearch
    port: 9300
  indices:
    source: /etc/raptor/indices.json
    names:
      object:
        index: objects
        type: device
      data:
        index: data
        type: record
