
spring:
  devtools:
    restart:
      enabled: true
      trigger-file: raptor-inventory-1.0.jar
      additional-paths: target

  profiles: default
  data:
    mongodb:
      host: mongo
      port: 27017
      database: raptor
  #    username: admin
  #    password: admin

server:
  contextPath: /inventory
  port: 8060
  address: inventory
  error:
    whitelabel:
      enabled: true

logging:
  level:
#    root: INFO
#    org.springframework.security: DEBUG
    org.createnet.raptor.profile: DEBUG
    org.createnet.raptor: DEBUG
    org.springframework.data.mongodb.core.index: OFF

raptor:
    url: http://rproxy
    auth:
        header: Authorization
        headerPrefix: Bearer
