
spring:
  devtools:
    restart:
      enabled: true
      trigger-file: raptor-${spring.config.name}-1.0.jar
      additional-paths: target

  data:
    mongodb:
      host: mongo
      port: 27017
      database: raptor


server:
  port: 80
  contextPath: /${spring.config.name}
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: true

logging:
  level:
    org.createnet.raptor: DEBUG


raptor:
  url: http://rproxy

  dispatcher:
    protocol: mqtt
    username: system
    password: system123
    uri: tcp://broker:1883

  auth:
    admin:
      enabled: true
      username: admin
      password: admin
      email: admin@raptor.local
    header: Authorization
    headerPrefix: Bearer
    # A secret used application wide for login token generation, keep it really secret
    secret: Voi che vivete sicuri Nelle vostre tiepide case
    # TTL in seconds, 1800 = 30 minutes
    expiration: 1800
