
spring:
  devtools:
    restart:
      enabled: true
      trigger-file: raptor-${spring.config.name}-1.0.jar
      additional-paths: target

  data:
    mongodb:
      host: mongo
      port: 27017
      database: raptor

server:
  web: true
  port: 80
  contextPath: /
  # contextPath: /${spring.config.name}
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: true

  tomcat:
    max-threads: 48

logging:
  level:
    org.createnet.raptor: DEBUG
    org.spring: WARN
    root: WARN

raptor:
  url: http://apigateway

  dispatcher:
    protocol: mqtt
    uri: tcp://broker:1883

  auth:

    users:
      - username: admin
        password: admin
        email: admin@raptor.local
        roles:
          - super_admin
    #   - username: service
    #     password: service
      - username: service
        password: s3rvice
        email: service@raptor.local
        roles:
          - super_admin
        lock: true
        type: service

    header: Authorization
    headerPrefix: Bearer

    # Used for login token generation
    secret: ${random.value}
    # TTL in seconds, 1800 = 30 minutes
    expiration: 1800

  broker:
    artemis: file:///etc/raptor/broker.xml
