
spring:
  profiles: default

server:
  error:
    whitelabel:
      enabled: true

logging:
  level:
    org.createnet.raptor: DEBUG

raptor:

  dispatcher:
    protocol: mqtt
    username: system
    password: system123
    uri: tcp://broker:1883

  url: http://rproxy
  admin:
    enabled: true
    username: admin
    password: admin
    email: admin@raptor.local

  token: jkvnsdklfnsdjk34tn34ornv8349fgn4w59gnw35g034g59n3590thg3w94g34qkk34tk

  auth:
    header: Authorization
    headerPrefix: Bearer
    # A secret used application wide for login token generation, keep it really secret
    secret: Voi che vivete sicuri Nelle vostre tiepide case
    # TTL in seconds, 1800 = 30 minutes
    expiration: 1800
    route:
      authentication:
        path: /login
        refresh: /refresh
