apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.1.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apigateway
    spec:
      containers:
      - args:
        - nginx
        - -g
        - daemon off;
        image: nginx
        name: apigateway
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: apigateway-claim0
      restartPolicy: Always
      volumes:
      - name: apigateway-claim0
        persistentVolumeClaim:
          claimName: apigateway-claim0
status: {}
