apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.1.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: broker
    spec:
      containers:
      - image: raptorbox/standalone:v4
        name: broker
        ports:
        - containerPort: 1883
        resources: {}
        volumeMounts:
        - mountPath: /etc/raptor
          name: broker-claim0
        - mountPath: /data
          name: broker-claim1
      restartPolicy: Always
      volumes:
      - name: broker-claim0
        persistentVolumeClaim:
          claimName: broker-claim0
      - name: broker-claim1
        persistentVolumeClaim:
          claimName: broker-claim1
status: {}
