apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.1.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: raptor
        - name: MYSQL_ROOT_PASSWORD
          value: raptor
        - name: MYSQL_USERNAME
          value: root
        image: mariadb:latest
        name: mariadb
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mariadb-claim0
      restartPolicy: Always
      volumes:
      - name: mariadb-claim0
        persistentVolumeClaim:
          claimName: mariadb-claim0
status: {}
