version: "2"

networks:
  raptor_net:
    driver: bridge

services:

  broker:
    image: raptorbox/broker:v4
    ports:
      - 1883:1883
    volumes:
      - ../../config:/etc/raptor
      - ../../data:/data
    networks:
      - raptor_net

  auth:
    image: raptorbox/auth:v4
    volumes:
      - ../../config:/etc/raptor
    links:
      - mariadb
    depends_on:
      - mariadb
      - broker
    networks:
      - raptor_net

  action:
    image: raptorbox/action:v4
    volumes:
      - ../../config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
      - auth
    networks:
      - raptor_net

  inventory:
    image: raptorbox/inventory:v4
    volumes:
      - ../../config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
      - auth
    networks:
      - raptor_net

  profile:
    image: raptorbox/profile:v4
    volumes:
      - ../../config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
      - auth
    networks:
      - raptor_net

  stream:
    image: raptorbox/stream:v4
    volumes:
      - ../../config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
      - auth
    networks:
      - raptor_net

  tree:
    image: raptorbox/tree:v4
    volumes:
      - ../../config:/etc/raptor
    links:
      - mongo
    depends_on:
      - mongo
      - auth
    networks:
      - raptor_net

  apigateway:
    image: raptorbox/gateway:v4
    ports:
        - 80:80
    volumes:
      - ../../config:/etc/raptor
    depends_on:
        - broker
        - auth
    networks:
      - raptor_net

  curl:
    image: byrnedo/alpine-curl
    volumes:
      - ../../:/raptor
    networks:
      - raptor_net

  mariadb:
    image: mariadb:latest
    volumes:
      - ../../data/mariadb:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: raptor
      MYSQL_DATABASE: raptor
    networks:
      - raptor_net

  mongo:
    image: mongo:3
    volumes:
      - ../../data/mongodb:/data/db
    command: --smallfiles --setParameter failIndexKeyTooLong=false
    networks:
      - raptor_net
